### ISSUE TITLE
No entiendo...

### ISSUE THREAD

**Issue by MegaBrunx** [Iakobs/godot-google-play-game-services-plugin#1]
Hola Amigo.

Aqui un compadre español. Estoy intentando usar tu plugin para usar los servicios en mi juego y no me aclaro.

Que metodos son los que tengo que usar para cada necesidad, o en que orden?.

La configuracion esta lista, es el uso de las funciones del plugin lo que no entiendo.

Gracias

**Comment by Iakobs** [comment]
Hola @MegaBrunx

gracias por tu interés! Este repositorio es para el plugin de godot, que no es más que un añadido para ejemplificar el uso con el [plugin de Android](https://github.com/Iakobs/godot-google-play-game-services-android-plugin), que es el verdadero plugin que se conecta a los servicios de Google. Así pues, este plugin de godot, NO es necesario. Necesitas el otro, el de Android.

Dicho esto, en el proyecto de demo que hay en este repositorio, si sigues el código, podrás ver cómo se usa. No hay un orden concreto. Aún tengo que actualizar la documentación con los pasos específicos, pero el plugin de Android funciona prácticamente igual que la API de Google, puedes mirar su guía [aquí](https://developers.google.com/games/services/android/quickstart?hl=en).

La integración y el uso del plugin es algo complicado, sobre todo si no se tiene mucha experiencia como desarrollador. Como digo, tengo previsto escribir una guía paso a paso, pero por ahora con el proyecto de demo, el código fuente del plugin de Android y la guía de Google, deberías poder hacerlo funcionar. Recuerda que también tienes que crear una cuenta de desarrollador de Google, crear una app en dev console y configurar el proyecto adecuadamente.

Saludos!

**Comment by MegaBrunx** [comment]
Hola.

Tengo la cuenta de desarrollador, todo configurado en google cloud, en godot he introducido las lineas necesarias en Manifest y strings.xml. He incluso he utilizado la estructura de codigo de tu demo dentro de mi proyecto y aun así tampoco he conseguido ni siquiera logearme. Cuando arranco la app en mi smartphone de pruebas (con la cuenta de tester incluida en dev console) Aparece el circulo girando (indicando que esta conectando) pero enseguida desaparece y no hace nada. Deberia salirme el mensaje del OAuth pero nada.

Le he dado mil vueltas a las instrucciones que proporcionas, a la estructura de tu proyecto, a las instrucciones de google para configurar el proyecto de los servicios de juegos y no consigo encontrar donde esta mi error. Bajo mi analisis todo esta correcto y deberia funcionar pero no lo hace.

Como puedo debugear para ver donde esta el error? Porque en el Output de Godot me da los prints de que se esta ejecutando las lineas pero no de los errores de logeo, es como si no obtuviera ninguna respuesta.

Te agradezco por adelantado tu trabajo en el plugin y la ayuda.

**Comment by Iakobs** [comment]
Perdona que tarde tanto en contestar, miraré a ver qué puede ser en cuanto tenga un hueco. Me sabe mal que no te funcione. Si quieres ver los logs a ver si hay algo allí que te de una pista, desde Android studio deberías poder verlos, conectando tu teléfono por usb o wifi. Me temo que debugar el código del plugin no sea posible, no lo he probado pero no parece algo fácil de hacer.

De todas formas, la configuración de Google puede ser muy caprichosa, hay que asegurarse sobre todo que la keystore que use godot para firmar la app (se define en las propiedades del editor, no del proyecto) sea la misma que tiene Google cloud en las credenciales, y que el nombre del paquete (com.godot.game creo que es por defecto) también coincida en las credenciales de Google cloud y del export configuration de godot. Esas dos cosas me dieron muchos problemas al principio.

Gracias por tu paciencia y por comentar tus problemas, me ayuda mucho a mejorar el plugin!

**Comment by Iakobs** [comment]
Hola @MegaBrunx voy a cerrar esta issue. Si te interesa, hay una nueva versión del plugin para godot 4.2+ [aquí](https://github.com/Iakobs/godot-play-game-services)
