### ISSUE TITLE
Any plans for a Godot 4.X version?

### ISSUE THREAD

**Issue by mathewcst** [Iakobs/godot-google-play-game-services-plugin#2]
Would love to use this plugin in a game but I use Godot 4.X. Any plans on updating?

**Comment by Iakobs** [comment]
Hi! First of all, thanks a lot for your interest!

Answering your request; yes, we have plans to update to godot 4, but following the recommendations of the Godot team, we are going to wait until version 4.1 is stable, so not yet.

We are going to focus first on integrating missing features from Game Services like cloud saves.

As I said, thanks again for your interest. I'm going to close the issue as well 😃
