### ISSUE TITLE
Signals data

### ISSUE THREAD

**Issue by Miskler** [Iakobs/godot-google-play-game-services-plugin#3]
Now, judging by the signals of the singleton input, they are just lying around stating facts. Nevertheless, I see from the code that some data is still being transferred to plugins.

It would not be bad to describe this in the plugin declaration, specify the type and preferably a little documentation of what the parameter means.

I came up with this question because it doesn't make sense to announce the entrance to Google games. Nevertheless, upon successful login to the corresponding plugin, an ID is still sent, it seems. Can you tell us more about it? I'm also wondering if I can get a username?

**Comment by Iakobs** [comment]
Hi @Miskler thanks a lot for your interest. I'm working right now on integrating this with Godot 4.2, and once that's done, I will definitely try to improve on the docs. Your suggestions are highly appreciated, I also think it will make sense to include what you said.

The android plugin, though, is basically a proxy between the google play services SDK and godot, and it's not doing anything fancy apart from logging. You can see it in the android plugin code at https://github.com/Iakobs/godot-google-play-game-services-android-plugin. Also, if you have more questions about the actual google API, you can also check their docs in the meantime at https://developers.google.com/games/services/android/quickstart?hl=en

**Comment by joelgomes1994** [comment]
I've rewritten and merged a new version in `main` from #5. It requires a new plugin [release binary](https://github.com/Iakobs/godot-google-play-game-services-android-plugin) and it's fully documented in the [README.md](https://github.com/Iakobs/godot-google-play-game-services-plugin/blob/main/README.md).
