### ISSUE TITLE
Wrong signal in singleton.gd

### ISSUE THREAD

**Issue by Molly-Rose-Pastel** [Iakobs/godot-google-play-game-services-plugin#7]
In line 84 and 85 of the singleton.gd is an error:
android_plugin.connect("leaderboardsLoadPlayerCenteredScores", self, "_on_leaderboards_load_player_centered_scores")
android_plugin.connect("leaderboardsLoadTopScores", self, "_on_leaderboards_load_top_scores")

should be:
android_plugin.connect("leaderboardsPlayerCenteredScoresLoaded", self, "_on_leaderboards_load_player_centered_scores")
android_plugin.connect("leaderboardsTopScoresLoaded", self, "_on_leaderboards_load_top_scores")

**Comment by Iakobs** [comment]
Hi @Molly-Rose-Pastel thanks a lot for noticing and pointing this out! I just pushed the fix, so it should be solved!
